from pydantic import BaseModel
import os
import pandas as pd
from fastapi import APIRouter, HTTPException

from app.core.database import db
from app.services.llm.factory import get_llm_provider
from app.services.insight_generator import generate_insights
from app.utils.code_executor import CodeExecutor
from app.utils.column_utils import correct_column_name
from app.utils.chart_selector import select_chart


class QueryRequest(BaseModel):
    dataset_id: str
    question: str


router = APIRouter()


@router.post("/")
async def run_query(request: QueryRequest):

    # Fetch dataset metadata
    dataset = await db.datasets.find_one({"dataset_id": request.dataset_id})

    if not dataset:
        raise HTTPException(status_code=404, detail="Dataset not found")

    file_path = dataset["stored_path"]

    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Dataset file missing")

    # Load dataset
    df = pd.read_csv(file_path)
    df = df.drop(columns=[col for col in df.columns if "sr" in col.lower()], errors="ignore")

    # Build schema info
    columns_info = "\n".join(
        [f"- {col} ({str(df[col].dtype)})" for col in df.columns]
    )

    prompt = f"""
    You are analyzing a pandas DataFrame named df.
    
    DATASET SCHEMA:
    {columns_info}
    
    User Question:
    {request.question}
    
    Generate pandas code to answer the question.
    
    Rules:
    - Use only the provided column names
    - Assign the final DataFrame to variable 'result'
    - Do not import libraries
    
    Return JSON in this format:
    
    {{
     "analysis_code": "pandas code assigning to result",
     "chart_type": "bar | line | pie | scatter",
     "x_column": "column name",
     "y_column": "column name",
     "insights": "short business insight"
    }}
    """

    # Call LLM planner
    provider = get_llm_provider()
    llm_output = await provider.generate_structured(prompt)

    print("LLM Output:", llm_output)

    analysis_code = llm_output["analysis_code"]
    
    if "head()" in analysis_code:
        return {
            "error": "Model failed to generate meaningful analysis",
            "suggestion": "Try asking a clearer analytical question"
        }
    
    if "level=" in analysis_code:
        raise Exception("Invalid pandas pattern generated by model")

    # Execute analysis safely
    try:
        execution_result = CodeExecutor.execute(
            analysis_code,
            df
        )

        # Convert result to dataframe
        result_df = pd.DataFrame(execution_result["data"])
       
        # remove pandas merge suffixes
        result_df.columns = [
            col.replace("_x", "").replace("_y", "")
            for col in result_df.columns
        ]

    except Exception as e:
        return {
            "error": "AI generated invalid analysis logic.",
            "details": str(e),
            "suggestion": "Try rephrasing your question."
        }

    # Correct hallucinated columns using RESULT dataframe
    llm_output["x_column"] = correct_column_name(
        llm_output.get("x_column", ""),
        result_df.columns
    )

    llm_output["y_column"] = correct_column_name(
        llm_output.get("y_column", ""),
        result_df.columns
    )

    print("Corrected columns:", llm_output["x_column"], llm_output["y_column"])

    x_column = str(llm_output.get("x_column", "")).strip()
    y_column = str(llm_output.get("y_column", "")).strip()
    
    # Intelligent fallback if LLM fails
    if not x_column or not y_column:
    
        numeric_cols = result_df.select_dtypes(include=["number"]).columns.tolist()
        categorical_cols = result_df.select_dtypes(exclude=["number"]).columns.tolist()
    
        if categorical_cols and numeric_cols:
            x_column = categorical_cols[0]
            y_column = numeric_cols[0]
    
        elif len(result_df.columns) >= 2:
            x_column = result_df.columns[0]
            y_column = result_df.columns[1]
    
    llm_output["x_column"] = x_column
    llm_output["y_column"] = y_column

    # Prevent identical columns
    if llm_output["x_column"] == llm_output["y_column"]:
        if len(result_df.columns) >= 2:
            llm_output["y_column"] = result_df.columns[1]

    print("Final columns for chart:", llm_output["x_column"], llm_output["y_column"])

    # Validate columns exist in result dataframe
    x_column = str(llm_output.get("x_column", ""))
    y_column = str(llm_output.get("y_column", ""))
    
    # Validate columns exist in result dataframe
    x_column = str(llm_output.get("x_column", "")).strip()
    y_column = str(llm_output.get("y_column", "")).strip()
    
    for col in [x_column, y_column]:
        if col not in result_df.columns:
            return {
                "error": f"Invalid column generated by AI: {col}",
                "suggestion": f"Available columns: {list(result_df.columns)}"
            }

    # Select best chart
    chart_type = select_chart(
        str(llm_output.get("chart_type", "bar")),
        x_column,
        y_column,
        result_df,
        request.question
    )

    print(result_df)
    print(result_df.dtypes)

    print("LLM chart:", llm_output["chart_type"])
    print("Selected chart:", chart_type)

    # Generate insights AFTER execution
    insights = await generate_insights(
        provider,
        result_df,
        request.question
    )

    return {
        "table": execution_result,
        "chart": {
            "chart_type": chart_type,
            "x_column": x_column,
            "y_column": y_column,
        },
        "insights": insights
    }