from pydantic import BaseModel
import pandas as pd
from fastapi import APIRouter, HTTPException

from app.core.database import db
from app.services.llm.factory import get_llm_provider
from app.services.insight_generator import generate_insights
from app.services.code_generator import generate_pandas_code
from app.services.query_planner import generate_query_plan

from app.utils.code_executor import CodeExecutor
from app.utils.column_utils import correct_column_name
from app.utils.chart_selector import select_chart


class QueryRequest(BaseModel):
    dataset_id: str
    question: str


router = APIRouter()


@router.post("/")
async def run_query(request: QueryRequest):

    # LOAD DATASET
    dataset = await db.datasets.find_one({"dataset_id": request.dataset_id})

    if not dataset:
        raise HTTPException(status_code=404, detail="Dataset not found")

    df = pd.DataFrame(dataset["data"])

    # Remove serial columns
    df = df.drop(
        columns=[col for col in df.columns if "sr" in col.lower()],
        errors="ignore"
    )

    # BUILD STRUCTURED SCHEMA
    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    categorical_cols = df.select_dtypes(exclude=["number"]).columns.tolist()

    columns_info = f"""
Numeric columns (metrics):
{numeric_cols}

Categorical columns (dimensions):
{categorical_cols}
"""

    provider = get_llm_provider()

    # QUERY PLANNER
    try:

        plan = await generate_query_plan(
            provider,
            request.question,
            columns_info
        )

        # normalize planner output
        if "dimensions" in plan and "dimension" not in plan:
            plan["dimension"] = plan["dimensions"]

        print("Query Plan:", plan)

    except Exception as e:

        return {
            "error": "Failed to generate query plan",
            "details": str(e)
        }

    # GENERATE PANDAS CODE
    try:

        analysis_code = generate_pandas_code(plan)

        print("Generated pandas code:", analysis_code)

    except Exception as e:

        return {
            "error": "Failed to generate analysis code",
            "details": str(e)
        }

    # EXECUTE ANALYSIS
    try:

        execution_result = CodeExecutor.execute(
            analysis_code,
            df
        )

        result_df = pd.DataFrame(execution_result["data"])

        # Remove pandas merge suffixes
        result_df.columns = [
            col.replace("_x", "").replace("_y", "")
            for col in result_df.columns
        ]

    except Exception as e:

        return {
            "error": "AI generated invalid analysis logic.",
            "details": str(e),
            "suggestion": "Try rephrasing your question."
        }
        
    # COLUMN DETECTION
    dimension = plan.get("dimension")
    metric = plan.get("metric")

    x_column = correct_column_name(dimension, result_df.columns)
    y_column = correct_column_name(metric, result_df.columns)

    print("Corrected columns:", x_column, y_column)

    x_column = str(x_column) if x_column else ""
    y_column = str(y_column) if y_column else ""

    # FALLBACK COLUMN SELECTION
    if not x_column or not y_column:

        numeric_cols = result_df.select_dtypes(include=["number"]).columns.tolist()
        categorical_cols = result_df.select_dtypes(exclude=["number"]).columns.tolist()

        if categorical_cols and numeric_cols:
            x_column = str(categorical_cols[0])
            y_column = str(numeric_cols[0])

        elif len(result_df.columns) >= 2:
            x_column = str(result_df.columns[0])
            y_column = str(result_df.columns[1])

    # Prevent identical columns

    if x_column == y_column and len(result_df.columns) >= 2:
        y_column = str(result_df.columns[1])

    print("Final columns for chart:", x_column, y_column)

    # VALIDATE COLUMNS
    for col in [x_column, y_column]:

        if col not in result_df.columns:

            return {
                "error": f"Invalid column generated by AI: {col}",
                "suggestion": f"Available columns: {list(result_df.columns)}"
            }

    # CHART SELECTION
    chart_type = select_chart(
        plan.get("chart_type", "bar"),
        x_column,
        y_column,
        result_df,
        request.question
    )

    print("Selected chart:", chart_type)

    # INSIGHT GENERATION
    insights = await generate_insights(
        provider,
        result_df,
        request.question
    )

    # RESPONSE
    return {
        "table": execution_result,
        "chart": {
            "chart_type": chart_type,
            "x_column": x_column,
            "y_column": y_column,
            "group_by": plan.get("group_by")
        },
        "insights": insights
    }
